function solidModelSolver = ...
    createSolidModelSolver...
    (...
        solidModelSolverEnum,...
        mechanicalModel,...
        problem,...
        varargin...
    )
%createSolidModelSolver Summary of this function goes here
%   Detailed explanation goes here

solidModelSolverName = char(solidModelSolverEnum);

solidModelSolverFactory = ...
    eval(['@(varargin)', solidModelSolverName,'(varargin{:});']);

solidModelSolver = ...
    solidModelSolverFactory...
    (...
        mechanicalModel,...
        problem,...
        varargin{:}...
    );

end

