function materialLaw = createMaterialLaw...
    (...
        materialLawEnum,...
        mesh,...
        material,...
        varargin...
    )

constructor = sprintf('materialLaws.( ''%s'' )', materialLawEnum);
materialLawFactory = createObjectFactory(constructor);
materialLaw = materialLawFactory(mesh, material, varargin{:});

end

