function errorOperation(msg)
%errorOperation Called when a operation failed.

error(...
    [...
        msg ' '...
        'Maybe the operation '...
        'is not implemented or even invalid.'...
    ]);

end
