#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Set initial condition
solidModel="$(grep -e '^solidModel[ ]*[^;]*;' constant/solidProperties | tr -s ' ' | cut -d' ' -f2 | cut -d';' -f1)"
rm -f 0/D*
echo "Running solidModel $solidModel"
if [ "$solidModel" == "nonLinearGeometryUpdatedLagrangian" ]
then
   cp 0/org/DD 0/DD
elif [ "$solidModel" == "nonLinearGeometryTotalLagrangianTotalDisplacement" ]
then
   cp 0/org/D 0/D
elif [ "$solidModel" == "nonLinearGeometryTotalLagrangian" ]
then
   cp 0/org/DD 0/DD
else
   echo "SolidModel not supported. Check the constant/solidModel file"
   exit 1
fi

# Run solver
runApplication solids4Foam
